=== jpschewe/fll-sw/src/fll/resources/fll.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns="" elementFormDefault="qualified">
 <xsd:element name="fll">
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref="Performance" />
    <xsd:element ref="subjectiveCategory" minOccurs="0"
     maxOccurs="unbounded" />
   </xsd:sequence>
   <xsd:attribute name="title" type="xsd:string" use="required" />
   <xsd:attribute name="revision" type="xsd:string" use="optional" />
   <xsd:attribute name="bracketSort" type="bracketSortType"
    default="SEEDING">
    <xsd:annotation>
     <xsd:documentation>
      The sort type for the brackets. Defaults to
      "SEEDING", which sorts
      teams based upon the seeding rounds.
     </xsd:documentation>
    </xsd:annotation>
   </xsd:attribute>
   <xsd:attribute name="winner" type="highlowType"
    default="HIGH">
    <xsd:annotation>
     <xsd:documentation>
      Determine which scores are "better". Default is for high scores to win,
      although one might want to use low scores for a golf tournament or
      drag race times.
     </xsd:documentation>
    </xsd:annotation>
   </xsd:attribute>
  </xsd:complexType>
 </xsd:element>

 <xsd:simpleType name="bracketSortType">
  <xsd:restriction base="xsd:string">
   <xsd:enumeration value="SEEDING" />
   <xsd:enumeration value="ALPHA_TEAM" />
   <xsd:enumeration value="RANDOM" />
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:element name="Performance">
  <xsd:complexType>
   <xsd:sequence>
    <xsd:sequence maxOccurs="unbounded">
     <xsd:sequence minOccurs="0" maxOccurs="unbounded">
      <xsd:element ref="goal" maxOccurs="unbounded" />
      <xsd:element ref="computedGoal" minOccurs="0"
       maxOccurs="unbounded" />
     </xsd:sequence>
     <xsd:sequence minOccurs="0" maxOccurs="unbounded">
      <xsd:element ref="restriction" maxOccurs="unbounded" />
     </xsd:sequence>
     <xsd:element ref="tiebreaker" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
   </xsd:sequence>
   <xsd:attribute name="minimumScore" type="xsd:decimal"
    default="0">
    <xsd:annotation>
     <xsd:documentation>
      minimum score allowed in the performance scoring
     </xsd:documentation>
    </xsd:annotation>
   </xsd:attribute>

   <xsd:attribute name="weight" type="xsd:float" default="1.0">
    <xsd:annotation>
     <xsd:documentation>
      Weight this category has. Should be a number
      between 0 and 1.
     </xsd:documentation>
    </xsd:annotation>
   </xsd:attribute>

  </xsd:complexType>
  <xsd:key name="performanceGoalKey">
   <xsd:annotation>
    <xsd:documentation>
     All performance goal names must be unique.
    </xsd:documentation>
   </xsd:annotation>
   <xsd:selector xpath="./goal|./computedGoal" />
   <xsd:field xpath="@name" />
  </xsd:key>
  <xsd:keyref name="performanceGoalRef" refer="performanceGoalKey">
   <xsd:selector xpath=".//term|.//goalRef" />
   <xsd:field xpath="@goal" />
  </xsd:keyref>
 </xsd:element>

 <xsd:element name="subjectiveCategory">
  <xsd:complexType>
   <xsd:sequence maxOccurs="unbounded">
    <xsd:sequence minOccurs="0" maxOccurs="unbounded">
     <xsd:element ref="goal" maxOccurs="unbounded" />
     <xsd:element ref="computedGoal" minOccurs="0"
      maxOccurs="unbounded" />
    </xsd:sequence>
   </xsd:sequence>
   <xsd:attribute name="name" type="databaseName" use="required" />
   <xsd:attribute name="title" type="xsd:string" use="required" />

   <xsd:attribute name="weight" type="xsd:float" default="1.0">
    <xsd:annotation>
     <xsd:documentation>
      Weight this category has. Should be a number
      between 0 and 1.
     </xsd:documentation>
    </xsd:annotation>
   </xsd:attribute>
  </xsd:complexType>
  <xsd:key name="subjectiveGoalKey">
   <xsd:annotation>
    <xsd:documentation>
     All subjective goal names must be unique within a
     category.
    </xsd:documentation>
   </xsd:annotation>
   <xsd:selector xpath="./goal|./computedGoal" />
   <xsd:field xpath="@name" />
  </xsd:key>
  <xsd:keyref name="subjectiveGoalRef" refer="subjectiveGoalKey">
   <xsd:selector xpath=".//term|.//goalRef" />
   <xsd:field xpath="@goal" />
  </xsd:keyref>
 </xsd:element>

 <xsd:element name="goal">
  <xsd:annotation>
   <xsd:documentation>
    A goal is something that the team may be scored
    on. A goal has a
    maximum and a minimum that define what values are
    allowed. It also
    has a multiplier for cases where this goal is used
    to count things.
    If there are no value child elements, then the score
    is determined
    by multiplying the count, in the range min to max, by
    the
    multiplier. If there are child elements, the score is the score
    associated with the choosen child element times the multiplier.

    The
    order of the goals in the XML document specifies the order of
    the
    goals on the score sheet.
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element name="value" minOccurs="0" maxOccurs="unbounded">
     <xsd:complexType>
      <xsd:attribute name="score" type="xsd:integer"
       default="0">
       <xsd:annotation>
        <xsd:documentation>
         The score one gets for this value of an
         enumerated goal.
        </xsd:documentation>
       </xsd:annotation>
      </xsd:attribute>
      <xsd:attribute name="title" type="xsd:string" use="required">
       <xsd:annotation>
        <xsd:documentation>
         The title to display for this value.
        </xsd:documentation>
       </xsd:annotation>
      </xsd:attribute>
      <xsd:attribute name="value" type="xsd:string" use="required">
       <xsd:annotation>
        <xsd:documentation>
         The value to store in the database for this
         value.
        </xsd:documentation>
       </xsd:annotation>
      </xsd:attribute>
     </xsd:complexType>
    </xsd:element>
   </xsd:sequence>
   <xsd:attribute name="name" type="databaseName" use="required" />

   <xsd:attribute name="title" type="xsd:string" use="required" />

   <xsd:attribute name="description" type="xsd:string" />

   <xsd:attribute name="min" type="xsd:integer" default="0">
    <xsd:annotation>
     <xsd:documentation>
      The minimum raw score for this goal. Ignored if
      enumerated values
      exist
     </xsd:documentation>
    </xsd:annotation>
   </xsd:attribute>

   <xsd:attribute name="max" type="xsd:integer" default="1">
    <xsd:annotation>
     <xsd:documentation>
      The maximum raw score for this goal. Ignored if
      enumerated values
      exist
     </xsd:documentation>
    </xsd:annotation>
   </xsd:attribute>

   <xsd:attribute name="multiplier" type="xsd:decimal"
    default="1" />

   <xsd:attribute name="initialValue" type="xsd:integer"
    default="0">
    <xsd:annotation>
     <xsd:documentation>
      Used to initialize the counters in the score
      entry web page.
      Ignored for subjective goals.
     </xsd:documentation>
    </xsd:annotation>
   </xsd:attribute>

  </xsd:complexType>
 </xsd:element>

 <xsd:element name="restriction">
  <xsd:annotation>
   <xsd:documentation>
    A polynomial with an upper and lower bound used to
    determine if the
    restriction is violated. Lower bound and upper bound
    are inclusive.
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType>
   <xsd:complexContent>
    <xsd:extension base="polynomial">
     <xsd:attribute name="lowerBound" type="xsd:decimal"
      default="-512" />
     <xsd:attribute name="upperBound" type="xsd:decimal"
      default="512" />
     <xsd:attribute name="message" type="xsd:string" use="required" />
    </xsd:extension>
   </xsd:complexContent>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name="term">
  <xsd:complexType>
   <xsd:attribute name="coefficient" type="xsd:decimal"
    default="1" />
   <xsd:attribute name="goal" type="databaseName" use="required" />
   <xsd:attribute name="scoreType" type="goalScoreType"
    use="required" />
   <xsd:attribute name="floatingPoint" type="floatingPointType"
    default="truncate" />
  </xsd:complexType>
 </xsd:element>

 <xsd:simpleType name="goalScoreType">
  <xsd:annotation>
   <xsd:documentation>
    What score from the goal should be used? The 'raw'
    score or the
    'computed' score. Default is set to 'computed' to
    support backwards
    compatibility
   </xsd:documentation>
  </xsd:annotation>
  <xsd:restriction base="xsd:string">
   <xsd:enumeration value='computed' />
   <xsd:enumeration value='raw' />
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="floatingPointType">
  <xsd:annotation>
   <xsd:documentation>
    How floating point data should be handled for an
    operation. If set
    to 'decimal', then just compute floating point
    values. If set to
    'round', then round the value to the nearest
    integer. If set to
    'truncate', then truncate the value. Default is
    set to 'truncate'
    for the standard usage for most tournaments.
   </xsd:documentation>
  </xsd:annotation>
  <xsd:restriction base="xsd:string">
   <xsd:enumeration value='decimal' />
   <xsd:enumeration value='round' />
   <xsd:enumeration value='truncate' />
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:element name="tiebreaker">
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element name="test" maxOccurs="unbounded">
     <xsd:complexType>
      <xsd:annotation>
       <xsd:documentation>
        Need to add a winner attribute to the
        polynomial to be able to
        determine the winner of a tiebreaker.
       </xsd:documentation>
      </xsd:annotation>
      <xsd:complexContent>
       <xsd:extension base="polynomial">
        <xsd:attribute name="winner" type="highlowType"
         use="required" />
       </xsd:extension>
      </xsd:complexContent>
     </xsd:complexType>
    </xsd:element>
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>

 <xsd:complexType name="polynomial">
  <xsd:annotation>
   <xsd:documentation>
    A simple polynomial to be used in multiple places.
    Terms and
    constants are allowed in a polynomial.
   </xsd:documentation>
  </xsd:annotation>
  <xsd:sequence minOccurs="0" maxOccurs="unbounded">
   <xsd:element ref="term" minOccurs="0" maxOccurs="unbounded" />
   <xsd:element name="constant" minOccurs="0" maxOccurs="unbounded">
    <xsd:complexType>
     <xsd:attribute name="value" type="xsd:decimal" />
    </xsd:complexType>
   </xsd:element>
  </xsd:sequence>
 </xsd:complexType>

 <xsd:complexType name="polynomialWithVariables">
  <xsd:annotation>
   <xsd:documentation>
    A polynomial that can have variables references.
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexContent>
   <xsd:extension base="polynomial">
    <xsd:sequence minOccurs="0" maxOccurs="unbounded">
     <xsd:element ref="variableRef" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
   </xsd:extension>
  </xsd:complexContent>
 </xsd:complexType>

 <xsd:element name="variableRef">
  <xsd:complexType>
   <xsd:attribute name="coefficient" type="xsd:decimal"
    default="1" />
   <xsd:attribute name="variable" type="databaseName" use="required" />
   <xsd:attribute name="floatingPoint" type="floatingPointType"
    default="truncate" />
  </xsd:complexType>
 </xsd:element>

 <xsd:element name="computedGoal">
  <xsd:annotation>
   <xsd:documentation>
    A computed goal contains 0 or more variable
    declarations and then a
    switch statement.
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref="variable" minOccurs="0" maxOccurs="unbounded" />
    <xsd:element ref="switch" />
   </xsd:sequence>
   <xsd:attribute name="name" type="databaseName" use="required" />
   <xsd:attribute name="title" type="xsd:string" use="required" />
   <xsd:attribute name="description" type="xsd:string" />
  </xsd:complexType>
  <xsd:key name="variableKey">
   <xsd:annotation>
    <xsd:documentation>
     All variable names must be unique.
    </xsd:documentation>
   </xsd:annotation>
   <xsd:selector xpath="./variable" />
   <xsd:field xpath="@name" />
  </xsd:key>
  <xsd:keyref name="variableRef" refer="variableKey">
   <xsd:selector xpath=".//variableRef" />
   <xsd:field xpath="@variable" />
  </xsd:keyref>
 </xsd:element>

 <xsd:element name="switch">
  <xsd:annotation>
   <xsd:documentation>
    A switch statement has 0 or more cases and a
    default
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref="case" minOccurs="0" maxOccurs="unbounded" />
    <xsd:element name="default" type="polynomialWithVariables" />
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name="variable">
  <xsd:complexType>
   <xsd:complexContent>
    <xsd:extension base="polynomial">
     <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:extension>
   </xsd:complexContent>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name="case">
  <xsd:annotation>
   <xsd:documentation>
    A case has a condition and a result or a switch
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:choice>
     <xsd:element ref="condition" />
     <xsd:element ref="enumCondition" />
    </xsd:choice>
    <xsd:choice>
     <xsd:element name="result" type="polynomialWithVariables" />
     <xsd:element ref="switch" />
    </xsd:choice>
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name="condition">
  <xsd:annotation>
   <xsd:documentation>
    The condition for a case in a switch. A condition
    represents an
    inequality test that evaluates to a boolean. This is a
    comparison of
    two numbers (represented as polynomials).
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element name="left" type="polynomialWithVariables" />
    <xsd:choice>
     <xsd:element name="less-than" />
     <xsd:element name="less-than-or-equal" />
     <xsd:element name="greater-than" />
     <xsd:element name="greater-than-or-equal" />
     <xsd:element name="equal-to" />
     <xsd:element name="not-equal-to" />
    </xsd:choice>
    <xsd:element name="right" type="polynomialWithVariables" />
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name="enumCondition">
  <xsd:annotation>
   <xsd:documentation>
    A comparison of the value of an enumerated goal
    and a string
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element name="left" type="stringOrGoalRef" />
    <xsd:choice>
     <xsd:element name="equal-to" />
     <xsd:element name="not-equal-to" />
    </xsd:choice>
    <xsd:element name="right" type="stringOrGoalRef" />
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>

 <xsd:complexType name="stringOrGoalRef">
  <xsd:sequence>
   <xsd:choice>
    <xsd:element name="goalRef">
     <xsd:complexType>
      <xsd:attribute name="goal" type="databaseName" use="required" />
     </xsd:complexType>
    </xsd:element>
    <xsd:element name="stringConstant">
     <xsd:complexType>
      <xsd:attribute name="value" type="xsd:string" use="required" />
     </xsd:complexType>
    </xsd:element>
   </xsd:choice>
  </xsd:sequence>
 </xsd:complexType>

 <xsd:simpleType name="databaseName">
  <xsd:restriction base="xsd:string">
   <xsd:pattern value="\p{L}[\p{L}\p{Nd}_]*" />
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="highlowType">
  <xsd:restriction base="xsd:string">
   <xsd:enumeration value="HIGH" />
   <xsd:enumeration value="LOW" />
  </xsd:restriction>
 </xsd:simpleType>

</xsd:schema>

=== jpschewe/fll-sw/src/fll/resources/challenge-descriptors/fll-2010-body_forward.xml
<?xml version="1.0"?>
<fll
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  title="2010 MN FIRST LEGO League Tournament"
  xsi:noNamespaceSchemaLocation="http://fll-sw.sourceforge.net/fll.xsd"
  revision="Rev: 5"
  schemaVersion="1">

  <Performance
    minimumScore="0"
    weight="1.0">

    <goal
      name="common_bone_repair"
      title="Common Arm Bone Repair"
      multiplier="25" />

    <goal
      name="bone_bridge_inserted"
      title="Leg Bone Bridge Inserted"
      multiplier="15" />

    <goal
      name="goal_scored"
      title="Goal Scored"
      multiplier="25" />

    <!-- if goal_scored, must have bone_bridge_inserted -->
    <restriction
      lowerBound="0"
      upperBound="1"
      message="You cannot have the Goal Scored without the Bone Bridge Inserted">
      <term>
        <constant value="-1" />
        <goalRef
          goal="goal_scored"
          scoreType="raw" />
      </term>
      <term>
        <constant value="1" />
        <goalRef
          goal="bone_bridge_inserted"
          scoreType="raw" />
      </term>
    </restriction>

    <goal
      name="rapid_blood_screening_syringe"
      title="Syringe Ever In Base"
      multiplier="25" />

    <goal
      name="rapid_blood_screening_cells"
      title="White and No Red Blood Cells in Patient Area"
      multiplier="15" />

    <goal
      name="red_blood_cells"
      title="Red Blood Cells"
      multiplier="5"
      max="8" />

    <goal
      name="bad_cell_destruction"
      title="Bad Cell Destruction"
      initialValue="0">
      <value
        score="25"
        title="Destruction"
        value="destruction" />
      <value
        score="20"
        title="Id"
        value="identification" />
      <value
        score="0"
        title="None"
        value="none" />
    </goal>

    <goal
      name="mechanical_arm_patent"
      title="Mechanical Arm Holding Patent"
      multiplier="25" />

    <goal
      name="cardiac_patch"
      title="Cardiac Patch"
      multiplier="20" />

    <goal
      name="pace_maker"
      title="Pace Maker"
      multiplier="25" />

    <goal
      name="nerve_mapping"
      title="Nerve Mapping"
      multiplier="15" />

    <goal
      name="object_control"
      title="Door Control Through Thought"
      multiplier="20" />

    <goal
      name="medicine_part1"
      title="Medicine Auto-dispensing: Blue and Whites off, pinks on"
      multiplier="25" />

    <goal
      name="medicine_part2"
      title="Blue/White/Container in Patient Area"
      multiplier="5" />

    <goal
      name="sensitivity"
      title="Robotic Sensitivity - Weight Up"
      multiplier="25" />

    <goal
      name="professional_teamwork"
      title="Professional Teamwork"
      multiplier="25" />

    <goal
      name="bionic_eyes"
      title="Bionic Eye Touching Upper Body"
      multiplier="20" />

    <goal
      name="stent"
      title="Stent Inserted"
      multiplier="25" />


    <tiebreaker>
      <test winner="HIGH">
        <term>
          <goalRef
            goal="goal_scored"
            scoreType="computed" />
        </term>
      </test>

      <test winner="HIGH">
        <term>
          <goalRef
            goal="pace_maker"
            scoreType="computed" />
        </term>
      </test>

      <test winner="HIGH">
        <term>
          <goalRef
            goal="professional_teamwork"
            scoreType="computed" />
        </term>
      </test>

      <test winner="HIGH">
        <term>
          <goalRef
            goal="bad_cell_destruction"
            scoreType="computed" />
        </term>
      </test>

      <test winner="HIGH">
        <term>
          <goalRef
            goal="mechanical_arm_patent"
            scoreType="computed" />
        </term>
      </test>

    </tiebreaker>

  </Performance>

  <subjectiveCategory
    name="teamwork"
    title="Teamwork"
    weight="1.0">
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="roles"
      title="Roles and Responsibilities">
    </goal>
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="professionalism"
      title="Gracious Professionalism">
    </goal>
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="dynamics"
      title="Problem Solving &amp; Team Dynamics &amp; Communications">
    </goal>
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="confidence"
      title="Confidence &amp; Enthusiasm">
    </goal>
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="fll_values"
      title="FLL Values">
    </goal>
  </subjectiveCategory>


  <subjectiveCategory
    name="robustdesign"
    title="Design"
    weight="0.5">
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="strategy"
      title="Strategy, Process, Problem Solving">
    </goal>
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="locomotion"
      title="Locomotion and Navigation">
    </goal>
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="design_kids"
      title="Kids Did the Work">
    </goal>
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="structural"
      title="Structural">
    </goal>
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="overall_design"
      title="Overall Design">
    </goal>
  </subjectiveCategory>


  <subjectiveCategory
    name="programming"
    title="Programming"
    weight="0.5">
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="programming_strategy"
      title="Strategy, Process, Problem Solving" />
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="useoflanguage"
      title="Language Use, Modularity/Abstraction">
    </goal>
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="programming_kids"
      title="Kids Did the Work">
    </goal>
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="sensorcontrol"
      title="Sensor Control">
    </goal>
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="design"
      title="Overall Design">
    </goal>
  </subjectiveCategory>

  <subjectiveCategory
    name="research"
    title="Research Project Assessment"
    weight="1.0">
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="research"
      title="Research">
    </goal>
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="innovative_solution"
      title="Innovative Solution">
    </goal>
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="background"
      title="Background, Data and Graphics">
    </goal>
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="creative"
      title="Quality of Presentation/Creative Presentation">
    </goal>
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="sharing"
      title="Sharing">
    </goal>
  </subjectiveCategory>


</fll>

=== jpschewe/fll-sw/src/main/resources/fll/resources/challenge-descriptors/rec-2014.xml
<?xml version="1.0"?>
<fll
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  title="Minnesota Renewable Energy Challenge: 2014"
  xsi:noNamespaceSchemaLocation="http://fll-sw.sourceforge.net/fll.xsd"
  revision="1"
  schemaVersion="1">

  <Performance
    minimumScore="0"
    weight="0.35">

    <goal
      name="energy"
      title="Energy Output mWs"
      max="120000"
      scoreType="FLOAT" />

    <tiebreaker>
      <!-- should be empty, but not allowed by the schema -->
      <test winner="HIGH">
        <term>
          <goalRef
            goal="energy"
            scoreType="computed" />
        </term>
      </test>
    </tiebreaker>

  </Performance>

  <subjectiveCategory
    name="sail_car"
    title="Sail Car Challenge"
    weight="0.10">
    <goal
      initialValue="0"
      max="10"
      min="0"
      multiplier="10"
      name="construction"
      title="Construction">
    </goal>
    <goal
      initialValue="0"
      max="30"
      min="0"
      multiplier="1"
      name="distance"
      title="Farthest Distance Traveled">
    </goal>
  </subjectiveCategory>

  <subjectiveCategory
    name="turbine_documentation"
    title="Turbine Documentation"
    weight="0.15">
    <goal
      initialValue="0"
      max="10"
      min="0"
      multiplier="1"
      name="knowledge"
      title="Demonstrated Knowledge">
    </goal>
    <goal
      initialValue="0"
      max="10"
      min="0"
      multiplier="1"
      name="statement"
      title="Design Statement">
    </goal>
  </subjectiveCategory>

  <subjectiveCategory
    name="turbine_technical"
    title="Turbine Technical Review"
    weight="0.15">
    <goal
      initialValue="0"
      max="10"
      min="0"
      multiplier="1"
      name="blades"
      title="Blades">
    </goal>
    <goal
      initialValue="0"
      max="10"
      min="0"
      multiplier="1"
      name="drivetrain"
      title="Drive Train">
    </goal>
    <goal
      initialValue="0"
      max="10"
      min="0"
      multiplier="1"
      name="overall"
      title="Overall Construction Quality">
    </goal>
    <goal
      initialValue="0"
      max="10"
      min="0"
      multiplier="1"
      name="innovation"
      title="Innovation">
    </goal>
    <goal
      initialValue="0"
      max="10"
      min="0"
      multiplier="1"
      name="material"
      title="Material Selection">
    </goal>
  </subjectiveCategory>

  <subjectiveCategory
    name="weightlifter"
    title="Weightlifter Challenge"
    weight="0.10">
    <goal
      initialValue="0"
      max="75"
      min="0"
      multiplier="1"
      name="washers"
      title="Number of washers lifted">
    </goal>
    <goal
      initialValue="0"
      max="10"
      min="0"
      multiplier="7.5"
      name="construction"
      title="Construction">
    </goal>
    <goal
      initialValue="0"
      max="10"
      min="0"
      multiplier="15"
      name="teamwork"
      title="Teamwork">
    </goal>
  </subjectiveCategory>

  <subjectiveCategory
    name="wind_farm"
    title="Wind Farm Siting Challenge"
    weight="0.15">
    <goal
      initialValue="0"
      max="10"
      min="0"
      multiplier="1"
      name="team_dynamics"
      title="Team Dynamics">
    </goal>
    <goal
      initialValue="0"
      max="10"
      min="0"
      multiplier="1"
      name="integraion"
      title="Integration of Physical/Environmental Data">
    </goal>
    <goal
      initialValue="0"
      max="10"
      min="0"
      multiplier="1"
      name="political"
      title="Use of political, human built, environmental issues">
    </goal>
  </subjectiveCategory>

</fll>

=== jpschewe/fll-sw/src/test/resources/fll/xml/data/computed-goal-reference.xml
<?xml version="1.0"?>
<fll
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  title="Computed goal references computed goal"
  xsi:noNamespaceSchemaLocation="http://fll-sw.sourceforge.net/fll.xsd"
  schemaVersion="1">

  <Performance
    minimumScore="0"
    weight="1.0">

    <goal
      initialValue="0"
      max="8"
      min="0"
      multiplier="5"
      name="crates_base"
      title="Crates in Base" />

    <goal
      initialValue="0"
      max="8"
      min="0"
      multiplier="2"
      name="crates"
      title="Crates Elsewhere on Table" />


    <computedGoal
      name="computed1"
      title="computed1">
      <switch>
        <case>
          <condition>
            <left>
              <term>
                <goalRef
                  goal="crates_base"
                  scoreType="raw" />
              </term>
            </left>
            <equal-to />
            <right>
              <term>
                <constant value="0" />
              </term>
            </right>
          </condition>
          <result>
            <term>
              <constant value="10" />
            </term>
          </result>
        </case>
        <default>
          <term>
            <constant value="40" />
          </term>
        </default>
      </switch>
    </computedGoal>


    <computedGoal
      name="computed2"
      title="computed2">
      <switch>
        <case>
          <condition>
            <left>
              <term>
                <goalRef
                  goal="crates_base"
                  scoreType="raw" />
              </term>
            </left>
            <equal-to />
            <right>
              <term>
                <constant value="10" />
              </term>
            </right>
          </condition>
          <result>
            <term>
              <constant value="10" />
            </term>
          </result>
        </case>
        <default>
          <term>
            <constant value="40" />
          </term>
          <term>
            <constant value="5" />
            <goalRef
              goal="computed1"
              scoreType="computed" />
          </term>
        </default>
      </switch>
    </computedGoal>


    <tiebreaker>
      <test winner="HIGH">
        <term>
          <goalRef
            goal="crates_base"
            scoreType="computed" />
        </term>
      </test>
      <test winner="HIGH">
        <term>
          <goalRef
            goal="crates"
            scoreType="computed" />
        </term>
      </test>
    </tiebreaker>

  </Performance>

</fll>
