=== jpschewe/fll-sw/src/fll/resources/fll.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns="" elementFormDefault="qualified">
 <xsd:element name="fll">
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref="Performance" />
    <xsd:element ref="subjectiveCategory" minOccurs="0"
     maxOccurs="unbounded" />
   </xsd:sequence>
   <xsd:attribute name="title" type="xsd:string" use="required" />
   <xsd:attribute name="revision" type="xsd:string" use="optional" />
   <xsd:attribute name="bracketSort" type="bracketSortType"
    default="SEEDING">
    <xsd:annotation>
     <xsd:documentation>
      The sort type for the brackets. Defaults to
      "SEEDING", which sorts
      teams based upon the seeding rounds.
     </xsd:documentation>
    </xsd:annotation>
   </xsd:attribute>
   <xsd:attribute name="winner" type="highlowType"
    default="HIGH">
    <xsd:annotation>
     <xsd:documentation>
      Determine which scores are "better". Default is for high scores to win,
      although one might want to use low scores for a golf tournament or
      drag race times.
     </xsd:documentation>
    </xsd:annotation>
   </xsd:attribute>
  </xsd:complexType>
 </xsd:element>

 <xsd:simpleType name="bracketSortType">
  <xsd:restriction base="xsd:string">
   <xsd:enumeration value="SEEDING" />
   <xsd:enumeration value="ALPHA_TEAM" />
   <xsd:enumeration value="RANDOM" />
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:element name="Performance">
  <xsd:complexType>
   <xsd:sequence>
    <xsd:sequence maxOccurs="unbounded">
     <xsd:sequence minOccurs="0" maxOccurs="unbounded">
      <xsd:element ref="goal" maxOccurs="unbounded" />
      <xsd:element ref="computedGoal" minOccurs="0"
       maxOccurs="unbounded" />
     </xsd:sequence>
     <xsd:sequence minOccurs="0" maxOccurs="unbounded">
      <xsd:element ref="restriction" maxOccurs="unbounded" />
     </xsd:sequence>
     <xsd:element ref="tiebreaker" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
   </xsd:sequence>
   <xsd:attribute name="minimumScore" type="xsd:decimal"
    default="0">
    <xsd:annotation>
     <xsd:documentation>
      minimum score allowed in the performance scoring
     </xsd:documentation>
    </xsd:annotation>
   </xsd:attribute>

   <xsd:attribute name="weight" type="xsd:float" default="1.0">
    <xsd:annotation>
     <xsd:documentation>
      Weight this category has. Should be a number
      between 0 and 1.
     </xsd:documentation>
    </xsd:annotation>
   </xsd:attribute>

  </xsd:complexType>
  <xsd:key name="performanceGoalKey">
   <xsd:annotation>
    <xsd:documentation>
     All performance goal names must be unique.
    </xsd:documentation>
   </xsd:annotation>
   <xsd:selector xpath="./goal|./computedGoal" />
   <xsd:field xpath="@name" />
  </xsd:key>
  <xsd:keyref name="performanceGoalRef" refer="performanceGoalKey">
   <xsd:selector xpath=".//term|.//goalRef" />
   <xsd:field xpath="@goal" />
  </xsd:keyref>
 </xsd:element>

 <xsd:element name="subjectiveCategory">
  <xsd:complexType>
   <xsd:sequence maxOccurs="unbounded">
    <xsd:sequence minOccurs="0" maxOccurs="unbounded">
     <xsd:element ref="goal" maxOccurs="unbounded" />
     <xsd:element ref="computedGoal" minOccurs="0"
      maxOccurs="unbounded" />
    </xsd:sequence>
   </xsd:sequence>
   <xsd:attribute name="name" type="databaseName" use="required" />
   <xsd:attribute name="title" type="xsd:string" use="required" />

   <xsd:attribute name="weight" type="xsd:float" default="1.0">
    <xsd:annotation>
     <xsd:documentation>
      Weight this category has. Should be a number
      between 0 and 1.
     </xsd:documentation>
    </xsd:annotation>
   </xsd:attribute>
  </xsd:complexType>
  <xsd:key name="subjectiveGoalKey">
   <xsd:annotation>
    <xsd:documentation>
     All subjective goal names must be unique within a
     category.
    </xsd:documentation>
   </xsd:annotation>
   <xsd:selector xpath="./goal|./computedGoal" />
   <xsd:field xpath="@name" />
  </xsd:key>
  <xsd:keyref name="subjectiveGoalRef" refer="subjectiveGoalKey">
   <xsd:selector xpath=".//term|.//goalRef" />
   <xsd:field xpath="@goal" />
  </xsd:keyref>
 </xsd:element>

 <xsd:element name="goal">
  <xsd:annotation>
   <xsd:documentation>
    A goal is something that the team may be scored
    on. A goal has a
    maximum and a minimum that define what values are
    allowed. It also
    has a multiplier for cases where this goal is used
    to count things.
    If there are no value child elements, then the score
    is determined
    by multiplying the count, in the range min to max, by
    the
    multiplier. If there are child elements, the score is the score
    associated with the choosen child element times the multiplier.

    The
    order of the goals in the XML document specifies the order of
    the
    goals on the score sheet.
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element name="value" minOccurs="0" maxOccurs="unbounded">
     <xsd:complexType>
      <xsd:attribute name="score" type="xsd:integer"
       default="0">
       <xsd:annotation>
        <xsd:documentation>
         The score one gets for this value of an
         enumerated goal.
        </xsd:documentation>
       </xsd:annotation>
      </xsd:attribute>
      <xsd:attribute name="title" type="xsd:string" use="required">
       <xsd:annotation>
        <xsd:documentation>
         The title to display for this value.
        </xsd:documentation>
       </xsd:annotation>
      </xsd:attribute>
      <xsd:attribute name="value" type="xsd:string" use="required">
       <xsd:annotation>
        <xsd:documentation>
         The value to store in the database for this
         value.
        </xsd:documentation>
       </xsd:annotation>
      </xsd:attribute>
     </xsd:complexType>
    </xsd:element>
   </xsd:sequence>
   <xsd:attribute name="name" type="databaseName" use="required" />

   <xsd:attribute name="title" type="xsd:string" use="required" />

   <xsd:attribute name="description" type="xsd:string" />

   <xsd:attribute name="min" type="xsd:integer" default="0">
    <xsd:annotation>
     <xsd:documentation>
      The minimum raw score for this goal. Ignored if
      enumerated values
      exist
     </xsd:documentation>
    </xsd:annotation>
   </xsd:attribute>

   <xsd:attribute name="max" type="xsd:integer" default="1">
    <xsd:annotation>
     <xsd:documentation>
      The maximum raw score for this goal. Ignored if
      enumerated values
      exist
     </xsd:documentation>
    </xsd:annotation>
   </xsd:attribute>

   <xsd:attribute name="multiplier" type="xsd:decimal"
    default="1" />

   <xsd:attribute name="initialValue" type="xsd:integer"
    default="0">
    <xsd:annotation>
     <xsd:documentation>
      Used to initialize the counters in the score
      entry web page.
      Ignored for subjective goals.
     </xsd:documentation>
    </xsd:annotation>
   </xsd:attribute>

  </xsd:complexType>
 </xsd:element>

 <xsd:element name="restriction">
  <xsd:annotation>
   <xsd:documentation>
    A polynomial with an upper and lower bound used to
    determine if the
    restriction is violated. Lower bound and upper bound
    are inclusive.
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType>
   <xsd:complexContent>
    <xsd:extension base="polynomial">
     <xsd:attribute name="lowerBound" type="xsd:decimal"
      default="-512" />
     <xsd:attribute name="upperBound" type="xsd:decimal"
      default="512" />
     <xsd:attribute name="message" type="xsd:string" use="required" />
    </xsd:extension>
   </xsd:complexContent>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name="term">
  <xsd:complexType>
   <xsd:attribute name="coefficient" type="xsd:decimal"
    default="1" />
   <xsd:attribute name="goal" type="databaseName" use="required" />
   <xsd:attribute name="scoreType" type="goalScoreType"
    use="required" />
   <xsd:attribute name="floatingPoint" type="floatingPointType"
    default="truncate" />
  </xsd:complexType>
 </xsd:element>

 <xsd:simpleType name="goalScoreType">
  <xsd:annotation>
   <xsd:documentation>
    What score from the goal should be used? The 'raw'
    score or the
    'computed' score. Default is set to 'computed' to
    support backwards
    compatibility
   </xsd:documentation>
  </xsd:annotation>
  <xsd:restriction base="xsd:string">
   <xsd:enumeration value='computed' />
   <xsd:enumeration value='raw' />
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="floatingPointType">
  <xsd:annotation>
   <xsd:documentation>
    How floating point data should be handled for an
    operation. If set
    to 'decimal', then just compute floating point
    values. If set to
    'round', then round the value to the nearest
    integer. If set to
    'truncate', then truncate the value. Default is
    set to 'truncate'
    for the standard usage for most tournaments.
   </xsd:documentation>
  </xsd:annotation>
  <xsd:restriction base="xsd:string">
   <xsd:enumeration value='decimal' />
   <xsd:enumeration value='round' />
   <xsd:enumeration value='truncate' />
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:element name="tiebreaker">
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element name="test" maxOccurs="unbounded">
     <xsd:complexType>
      <xsd:annotation>
       <xsd:documentation>
        Need to add a winner attribute to the
        polynomial to be able to
        determine the winner of a tiebreaker.
       </xsd:documentation>
      </xsd:annotation>
      <xsd:complexContent>
       <xsd:extension base="polynomial">
        <xsd:attribute name="winner" type="highlowType"
         use="required" />
       </xsd:extension>
      </xsd:complexContent>
     </xsd:complexType>
    </xsd:element>
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>

 <xsd:complexType name="polynomial">
  <xsd:annotation>
   <xsd:documentation>
    A simple polynomial to be used in multiple places.
    Terms and
    constants are allowed in a polynomial.
   </xsd:documentation>
  </xsd:annotation>
  <xsd:sequence minOccurs="0" maxOccurs="unbounded">
   <xsd:element ref="term" minOccurs="0" maxOccurs="unbounded" />
   <xsd:element name="constant" minOccurs="0" maxOccurs="unbounded">
    <xsd:complexType>
     <xsd:attribute name="value" type="xsd:decimal" />
    </xsd:complexType>
   </xsd:element>
  </xsd:sequence>
 </xsd:complexType>

 <xsd:complexType name="polynomialWithVariables">
  <xsd:annotation>
   <xsd:documentation>
    A polynomial that can have variables references.
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexContent>
   <xsd:extension base="polynomial">
    <xsd:sequence minOccurs="0" maxOccurs="unbounded">
     <xsd:element ref="variableRef" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
   </xsd:extension>
  </xsd:complexContent>
 </xsd:complexType>

 <xsd:element name="variableRef">
  <xsd:complexType>
   <xsd:attribute name="coefficient" type="xsd:decimal"
    default="1" />
   <xsd:attribute name="variable" type="databaseName" use="required" />
   <xsd:attribute name="floatingPoint" type="floatingPointType"
    default="truncate" />
  </xsd:complexType>
 </xsd:element>

 <xsd:element name="computedGoal">
  <xsd:annotation>
   <xsd:documentation>
    A computed goal contains 0 or more variable
    declarations and then a
    switch statement.
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref="variable" minOccurs="0" maxOccurs="unbounded" />
    <xsd:element ref="switch" />
   </xsd:sequence>
   <xsd:attribute name="name" type="databaseName" use="required" />
   <xsd:attribute name="title" type="xsd:string" use="required" />
   <xsd:attribute name="description" type="xsd:string" />
  </xsd:complexType>
  <xsd:key name="variableKey">
   <xsd:annotation>
    <xsd:documentation>
     All variable names must be unique.
    </xsd:documentation>
   </xsd:annotation>
   <xsd:selector xpath="./variable" />
   <xsd:field xpath="@name" />
  </xsd:key>
  <xsd:keyref name="variableRef" refer="variableKey">
   <xsd:selector xpath=".//variableRef" />
   <xsd:field xpath="@variable" />
  </xsd:keyref>
 </xsd:element>

 <xsd:element name="switch">
  <xsd:annotation>
   <xsd:documentation>
    A switch statement has 0 or more cases and a
    default
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref="case" minOccurs="0" maxOccurs="unbounded" />
    <xsd:element name="default" type="polynomialWithVariables" />
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name="variable">
  <xsd:complexType>
   <xsd:complexContent>
    <xsd:extension base="polynomial">
     <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:extension>
   </xsd:complexContent>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name="case">
  <xsd:annotation>
   <xsd:documentation>
    A case has a condition and a result or a switch
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:choice>
     <xsd:element ref="condition" />
     <xsd:element ref="enumCondition" />
    </xsd:choice>
    <xsd:choice>
     <xsd:element name="result" type="polynomialWithVariables" />
     <xsd:element ref="switch" />
    </xsd:choice>
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name="condition">
  <xsd:annotation>
   <xsd:documentation>
    The condition for a case in a switch. A condition
    represents an
    inequality test that evaluates to a boolean. This is a
    comparison of
    two numbers (represented as polynomials).
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element name="left" type="polynomialWithVariables" />
    <xsd:choice>
     <xsd:element name="less-than" />
     <xsd:element name="less-than-or-equal" />
     <xsd:element name="greater-than" />
     <xsd:element name="greater-than-or-equal" />
     <xsd:element name="equal-to" />
     <xsd:element name="not-equal-to" />
    </xsd:choice>
    <xsd:element name="right" type="polynomialWithVariables" />
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name="enumCondition">
  <xsd:annotation>
   <xsd:documentation>
    A comparison of the value of an enumerated goal
    and a string
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element name="left" type="stringOrGoalRef" />
    <xsd:choice>
     <xsd:element name="equal-to" />
     <xsd:element name="not-equal-to" />
    </xsd:choice>
    <xsd:element name="right" type="stringOrGoalRef" />
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>

 <xsd:complexType name="stringOrGoalRef">
  <xsd:sequence>
   <xsd:choice>
    <xsd:element name="goalRef">
     <xsd:complexType>
      <xsd:attribute name="goal" type="databaseName" use="required" />
     </xsd:complexType>
    </xsd:element>
    <xsd:element name="stringConstant">
     <xsd:complexType>
      <xsd:attribute name="value" type="xsd:string" use="required" />
     </xsd:complexType>
    </xsd:element>
   </xsd:choice>
  </xsd:sequence>
 </xsd:complexType>

 <xsd:simpleType name="databaseName">
  <xsd:restriction base="xsd:string">
   <xsd:pattern value="\p{L}[\p{L}\p{Nd}_]*" />
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="highlowType">
  <xsd:restriction base="xsd:string">
   <xsd:enumeration value="HIGH" />
   <xsd:enumeration value="LOW" />
  </xsd:restriction>
 </xsd:simpleType>

</xsd:schema>

=== jpschewe/fll-sw/src/fll/resources/challenge-descriptors/hsr-2006-nano_quest.xml
<?xml version="1.0"?>
<fll
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  title="HSR 2006 Challenge: Nano Quest"
  xsi:noNamespaceSchemaLocation="http://fll-sw.sourceforge.net/fll.xsd"
  schemaVersion="1">

  <Performance
    minimumScore="0"
    weight="1.0">

    <goal
      name="pizza_off_pant_leg"
      title="Pizza Molecule Off Pant Leg"
      min="0"
      max="2"
      multiplier="10" />
    <goal
      name="pizza_in_dirt_trap"
      title="Pizza Molecule In Dirt Trap"
      min="0"
      max="2"
      multiplier="50" />
    <restriction
      lowerBound="0"
      upperBound="2"
      message="There cannot be more molecules in the dirt trap than off the pants">
      <term>
        <constant value="1" />
        <goalRef
          goal="pizza_off_pant_leg"
          scoreType="raw" />
      </term>
      <term>
        <constant value="-1" />
        <goalRef
          goal="pizza_in_dirt_trap"
          scoreType="raw" />
      </term>
    </restriction>

    <goal
      name="smart_medicine"
      title="Deliver Buckyball"
      multiplier="50" />

    <goal
      name="smart_medicine_retrieve"
      title="Retrieve Buckyball"
      multiplier="40" />

    <restriction
      lowerBound="0"
      upperBound="1"
      message="One must first retrieve buckyballs before they can be delivered">
      <term>
        <constant value="-1" />
        <goalRef
          goal="smart_medicine"
          scoreType="raw" />
      </term>
      <term>
        <constant value="1" />
        <goalRef
          goal="smart_medicine_retrieve"
          scoreType="raw" />
      </term>
    </restriction>

    <goal
      name="atomic_force"
      title="Free the Probe's Nanotip"
      multiplier="40" />

    <goal
      name="move_atoms_white"
      title="Scoring white atoms"
      min="0"
      max="8"
      multiplier="12" />

    <goal
      name="self_assembly"
      title="Self-alignment of Atoms"
      multiplier="25" />

    <goal
      name="atp_base"
      title="ATP molecules returned to base"
      multiplier="25"
      max="2" />

    <goal
      name="atp_frame"
      title="ATP molecules delivered"
      multiplier="20"
      max="2" />

    <restriction
      lowerBound="0"
      upperBound="2"
      message="One must first return the ATP molecules to the base before they can be delivered">
      <term>
        <constant value="1" />
        <goalRef
          goal="atp_base"
          scoreType="raw" />
      </term>
      <term>
        <constant value="-1" />
        <goalRef
          goal="atp_frame"
          scoreType="raw" />
      </term>
    </restriction>

    <goal
      name="dumper"
      title="Robot Emptied Dirt Dumper"
      multiplier="15" />

    <goal
      name="dirt_trap"
      title="Dirt Trap on Mark"
      multiplier="15" />

    <goal
      name="dirt_in_trap"
      title="Dirt in Dirt Trap"
      multiplier="7"
      max="8" />

    <goal
      name="dirt_elsewhere"
      title="Dirt Elsewhere"
      multiplier="3"
      max="8" />

    <restriction
      lowerBound="0"
      upperBound="8"
      message="There are a maximum of 8 dirt pieces on the table">
      <term>
        <constant value="1" />
        <goalRef
          goal="dirt_in_trap"
          scoreType="raw" />
      </term>
      <term>
        <constant value="1" />
        <goalRef
          goal="dirt_elsewhere"
          scoreType="raw" />
      </term>
    </restriction>

    <restriction
      lowerBound="0"
      upperBound="8"
      message="There are a maximum of 8 dirt pieces on the table">
      <term>
        <constant value="1" />
        <goalRef
          goal="dirt_in_base"
          scoreType="raw" />
      </term>
      <term>
        <constant value="1" />
        <goalRef
          goal="dirt_elsewhere"
          scoreType="raw" />
      </term>
    </restriction>

    <goal
      name="dirt_in_base"
      title="Dirt in Trap at Base"
      multiplier="5"
      max="8" />

    <restriction
      lowerBound="0"
      upperBound="8"
      message="If the dirt trap is at base, then the dirt in the trap counts for both Dirt in Dirt Trap and Dirt in Trap at Base">
      <term>
        <constant value="1" />
        <goalRef
          goal="dirt_in_trap"
          scoreType="raw" />
      </term>
      <term>
        <constant value="-1" />
        <goalRef
          goal="dirt_in_base"
          scoreType="raw" />
      </term>
    </restriction>

    <goal
      name="space_elevator"
      title="Operate Space Elevator"
      multiplier="40" />

    <goal
      name="nanotube_strength"
      title="Nanotube Strength">
      <value
        score="40"
        title="Supported by Cable"
        value="supported_by_cable" />
      <value
        score="20"
        title="Truck on Frame"
        value="truck_on_frame" />
      <value
        score="0"
        title="None"
        value="none" />
    </goal>

    <goal
      name="robot_type"
      title="Robot Type"
      multiplier="0"
      initialValue="1">
      <value
        score="1"
        title="RCX"
        value="rcx" />
      <value
        score="2"
        title="NXT"
        value="nxt" />
    </goal>

    <tiebreaker>
      <test winner="HIGH">
        <term>
          <goalRef
            goal="dirt_in_trap"
            scoreType="computed" />
        </term>
        <term>
          <goalRef
            goal="dirt_elsewhere"
            scoreType="computed" />
        </term>
        <term>
          <goalRef
            goal="dirt_in_base"
            scoreType="computed" />
        </term>
      </test>
      <test winner="HIGH">
        <term>
          <goalRef
            goal="pizza_in_dirt_trap"
            scoreType="computed" />
        </term>
      </test>
      <test winner="HIGH">
        <term>
          <goalRef
            goal="pizza_off_pant_leg"
            scoreType="computed" />
        </term>
      </test>
      <test winner="HIGH">
        <term>
          <goalRef
            goal="move_atoms_white"
            scoreType="computed" />
        </term>
      </test>
      <test winner="HIGH">
        <term>
          <goalRef
            goal="smart_medicine"
            scoreType="computed" />
        </term>
      </test>
      <test winner="HIGH">
        <term>
          <goalRef
            goal="atp_frame"
            scoreType="computed" />
        </term>
      </test>
      <test winner="HIGH">
        <term>
          <goalRef
            goal="smart_medicine_retrieve"
            scoreType="computed" />
        </term>
      </test>
      <test winner="HIGH">
        <term>
          <goalRef
            goal="atp_base"
            scoreType="computed" />
        </term>
      </test>
      <test winner="HIGH">
        <term>
          <goalRef
            goal="atomic_force"
            scoreType="computed" />
        </term>
      </test>
      <test winner="HIGH">
        <term>
          <goalRef
            goal="dumper"
            scoreType="computed" />
        </term>
      </test>
      <test winner="HIGH">
        <term>
          <goalRef
            goal="dirt_trap"
            scoreType="computed" />
        </term>
      </test>
      <test winner="HIGH">
        <term>
          <goalRef
            goal="self_assembly"
            scoreType="computed" />
        </term>
      </test>
      <test winner="HIGH">
        <term>
          <goalRef
            goal="nanotube_strength"
            scoreType="computed" />
        </term>
      </test>
    </tiebreaker>

  </Performance>

  <subjectiveCategory
    name="head2head"
    title="Head to Head"
    weight="5.5">
    <goal
      initialValue="0"
      max="700"
      min="0"
      multiplier="1"
      name="score"
      title="Score" />
    <goal
      initialValue="0"
      max="50"
      min="0"
      multiplier="1"
      name="bonus"
      title="Bonus" />
  </subjectiveCategory>

  <subjectiveCategory
    name="teamwork"
    title="Team Management"
    weight="1.0">
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="dynamics"
      title="Team Dynamics - Decision Making and Problem Solving" />
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="management"
      title="Team Management - Time, Task, and Project Management" />
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="structure"
      title="Team Structure - Roles and Participation" />
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="communication"
      title="Team Communication - Respect, Team Interaction and Confidence" />
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="general"
      title="Team Management General" />
  </subjectiveCategory>

  <subjectiveCategory
    name="research"
    title="Research Presentation"
    weight="2.5">
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="definition"
      title="Problem Definition" />
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="design"
      title="Design of Solution" />
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="evaluation"
      title="Evaluation of Solution" />
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="innovation"
      title="Innovation" />
    <goal
      initialValue="0"
      max="20"
      min="0"
      multiplier="1"
      name="communications"
      title="Communications" />
    <goal
      name="submitted"
      title="Documents Submitted Prior to Competition">
      <value
        score="33"
        value="yes"
        title="Yes" />
      <value
        score="0"
        value="no"
        title="No" />
    </goal>
  </subjectiveCategory>


</fll>
